# write by jbug

CC=gcc
CFLAGS=-g -Wall

test: test.c
	$(CC) -o test test.c $(CFLAGS)

p1: p1.c
	$(CC) -o p1 p1.c $(CFLAGS)

p2: p2.c
	$(CC) -o p2 p2.c $(CFLAGS)

p3: p3.c
	$(CC) -o p3 p3.c $(CFLAGS)

p4: p4.c
	$(CC) -o p4 p4.c $(CFLAGS)

p5: p5.c
	$(CC) -o p5 p5.c $(CFLAGS)

t1: t1.c
	$(CC) -o t1 t1.c $(CFLAGS)

t2: t2.c
	$(CC) -o t2 t2.c $(CFLAGS)

.PHONY:
clean:
	rm test p1 p2
