#
#   write by jbug

CC=gcc
FLAGS=-g -Wall
p1:p1.c
	$(CC) -o p1 p1.c $(FLAGS)

p2:p2.c
	$(CC) -o p2 p2.c $(FLAGS)

p3:p3.c
	$(CC) -o p3 p3.c $(FLAGS)

p4:p4.c
	$(CC) -o p4 p4.c $(FLAGS)

p5:p5.c
	$(CC) -o p5 p5.c $(FLAGS)

p6:p6.c
	$(CC) -o p6 p6.c $(FLAGS)

p7:p7.c
	$(CC) -o p7 p7.c $(FLAGS)

p8:p8.c
	$(CC) -o p8 p8.c $(FLAGS)

.PHONY:
clean:
	rm *.o p1 p2 p3 p4 p5 p6 p7 p8 -rf

