#
#   write by jbug

CC=gcc
FLAGS=-g -Wall

p1:p1.c
	$(CC) -o p1 p1.c $(FLAGS)

p2:p2.c
	$(CC) -o p2 p2.c $(FLAGS)

p3:p3.c
	$(CC) -o p3 p3.c $(FLAGS)

p4:p4.c
	$(CC) -o p4 p4.c $(FLAGS)

p5:p5.c
	$(CC) -o p5 p5.c $(FLAGS)

p6:p6.c
	$(CC) -o p6 p6.c $(FLAGS)

p7:p7.c
	$(CC) -o p7 p7.c $(FLAGS)

p8:p8.c
	$(CC) -o p8 p8.c $(FLAGS)

p9:p9.c
	$(CC) -o p9 p9.c $(FLAGS)

p10:p10.c
	$(CC) -o p10 p10.c $(FLAGS)

t1:t1.c
	$(CC) -o t1 t1.c $(FLAGS)

t2:t2.c
	$(CC) -o t2 t2.c $(FLAGS)

t3:t3.c
	$(CC) -o t3 t3.c $(FLAGS)

t4:t4.c
	$(CC) -o t4 t4.c $(FLAGS)

pt5:t5.c
	$(CC) -o t5 t5.c $(FLAGS)

t6:t6.c
	$(CC) -o t6 t6.c $(FLAGS)

t7:t7.c
	$(CC) -o t7 t7.c $(FLAGS)

t8:t8.c
	$(CC) -o t8 t8.c $(FLAGS)

t9:t9.c
	$(CC) -o t9 t9.c $(FLAGS)

t10:t10.c
	$(CC) -o t10 t10.c $(FLAGS)

t11:t11.c
	$(CC) -o t11 t11.c $(FLAGS)

t12:t12.c
	$(CC) -o t12 t12.c $(FLAGS)

t13:t13.c
	$(CC) -o t13 t13.c $(FLAGS)

t14:t14.c
	$(CC) -o t14 t14.c $(FLAGS)

t18:t18.c
	$(CC) -o t18 t18.c $(FLAGS)

t19:t19.c
	$(CC) -o t19 t19.c $(FLAGS)

test:test.c
	$(CC) -o test test.c $(FLAGS)

.PHONY:
clean:
	rm *.o

