#!/bin/bash

# launches the fcitx in gentoo.

export LC_ALL=zh_CN.utf8
export	XMODIFIERS="@im=fcitx"
export	XIM=fcitx
export	XIM_PROGRAM=fcitx
export	GTK_IM_MODULE=fcitx
export	QT_IM_MODULE=fcitx

fcitxlaunch="`which fcitx 2>/dev/null`"
if [ -n "$fcitxlaunch" ] && [ -x "$fcitxlaunch" ]; then
    $fcitxlaunch -r -d
fi

