# write by jbug
#

CC=gcc
CXX=g++
CFLAGS=-g -Wall
CXXFLAGS=-g -Wall
LIBS=-lncurses
INCS=

test: test.c
	$(CC) -o test test.c $(CFLAGS) $(LIBS) $(INCS)

hello: hello.c
	$(CC) -o hello hello.c $(CFLAGS) $(LIBS) $(INCS)

p1: p1.c
	$(CC) -o p1 p1.c $(CFLAGS) $(LIBS) $(INCS)

p2: p2.c
	$(CC) -o p2 p2.c $(CFLAGS) $(LIBS) $(INCS)

p3: p3.c
	$(CC) -o p3 p3.c $(CFLAGS) $(LIBS) $(INCS)

p4: p4.c
	$(CC) -o p4 p4.c $(CFLAGS) $(LIBS) $(INCS)

p5: p5.c
	$(CC) -o p5 p5.c $(CFLAGS) $(LIBS) $(INCS)

p6: p6.c
	$(CC) -o p6 p6.c $(CFLAGS) $(LIBS) $(INCS)

p7: p7.c
	$(CC) -o p7 p7.c $(CFLAGS) $(LIBS) $(INCS)

p8: p8.c
	$(CC) -o p8 p8.c $(CFLAGS) $(LIBS) $(INCS)

p9: p9.c
	$(CC) -o p9 p9.c $(CFLAGS) $(LIBS) $(INCS)

p10: p10.c
	$(CC) -o p10 p10.c $(CFLAGS) $(LIBS) $(INCS)

p11: p11.c
	$(CC) -o p11 p11.c $(CFLAGS) $(LIBS) $(INCS)

p12: p12.c
	$(CC) -o p12 p12.c $(CFLAGS) $(LIBS) $(INCS)

p13: p13.c
	$(CC) -o p13 p13.c $(CFLAGS) $(LIBS) $(INCS)

.PHONY:
clean:
	rm hello
